image: java:8-jdk

stages:
  - build
  - deploy
  
before_script:
  - chmod +x gradlew
  - echo $GPG_KEY_RING_FILE | base64 -d > /tmp/key
  - echo $JAVA_KEY_FILE | base64 -d > /tmp/key2
  - export TEST_PASSWORD=echo $ossrhPassword | base64 -d
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - echo "signing.keyId=$GPG_KEY_ID" >> gradle.properties
  - echo "signing.password=$GPG_PASSPHRASE" >> gradle.properties
  - echo "signing.secretKeyRingFile=/tmp/key" >> gradle.properties
  - echo "signing.keystorePath=/tmp/key2" >> gradle.properties
  - echo "signing.alias=$signing_alias" >> gradle.properties
  - echo "signing.keyStorePassword=$signing_keyStorePassword" >> gradle.properties
  - echo "cursegradle.api_token=$curse_api" >> gradle.properties
  - echo "ossrhUsername=$ossrhUsername" >> gradle.properties
  - echo "ossrhPassword=$TEST_PASSWORD" >> gradle.properties
  
cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - ./gradlew build
  only:
    variables:
        - $BUILD_MAVEN != "publish"
  except:
  - merge_requests
  artifacts:
    paths:
      - build/libs/
    expire_in: 2 months

curseforge:
  stage: deploy
  script:
    - ./gradlew build curseforge
  only:
    variables:
        - $BUILD_MAVEN == "curseforge"
  except:
  - merge_requests
  artifacts:
    paths:
      - build/libs/
    expire_in: 2 months

maven:
  stage: build
  script:
    - echo "isSonaType=true" >> gradle.properties
    - ./gradlew build uploadArchives
  only:
    variables:
        - $BUILD_MAVEN == "publish"
  except:
  - merge_requests
  artifacts:
    paths:
      - build/libs/
    expire_in: 2 months